### ISSUE TITLE
Cái này update lên version mới nhất của php với laravel được không vậy bạn 💯 

### ISSUE THREAD

**Issue by hungds99** [mondorae/luanvan2020#6]

**Comment by mondorae** [comment]
hello bạn,
Update lên thì vẫn được nhưng mà với bản laravel theo mình nhớ thì từ bản
7.0 trở lên có thay đổi 1 tí về lệnh route ấy. Nên muốn update thì phải sửa
lại một số lệnh :D
Cám ơn bạn đã quan tâm đến project của mình

Vào Th 6, 4 thg 6, 2021 vào lúc 15:38 Đinh Sỹ Hùng <
***@***.***> đã viết:

**Comment by hungds99** [comment]
![image](https://user-images.githubusercontent.com/34293141/120791335-49c24c00-c55e-11eb-8ea9-80503c04244a.png)
Mình chạy php version 7.1.3 thì bị lỗi này. Mình có search thì ra cái này https://stackoverflow.com/questions/42058233/php-compile-error-cannot-use-empty-array-elements-in-arrays
> NOTE: In PHP 7.2.15+, 7.3.2+, and 7.4.0+, the error message has been changed to report the line number of the previous valid element instead of the line number of the beginning of the array. While this may still be off by one or more lines, it is usually close enough to the problem to make it much easier to find.

Không biết có cách nào fix không nhỉ 
Cảm ơn bạn

**Comment by mondorae** [comment]
uầy mình bị dư dấu ',' ngay dòng 106 í nên nó lỗi :)))))))))))))

**Comment by hungds99** [comment]
Cảm ơn bạn đã support 👍  Chưa cài mấy cái PHP này bao giờ :) chiều giờ loay hoay cài lại version muốn mệt :))
